apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: drupal-cert
 namespace: default
spec:
 secretName: drupal-tls
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 commonName: reto2-telematica.me
 dnsNames:
 - reto2-telematica.me
